### ISSUE TITLE
Are you sure?

### ISSUE THREAD

**Issue by johnmcconnell** [lawrencewalters/algorithms#1]
Are you sure you want to make efficient algorithms in ruby?

**Comment by lawrencewalters** [comment]
You're killing me, smalls.

And, no, I don't, it's just the most familiar language for me right now.... Taking an algorithms class on coursera....

**Comment by johnmcconnell** [comment]
Ahh sorry! I was goofing around. Yeah, do it in whatever language you want! It's good stuff

**Comment by lawrencewalters** [comment]
Haaaaa. I knew you were goofing around.... But now I have to go re-learn c++ to save face.

**Comment by johnmcconnell** [comment]
lol!
